### ISSUE TITLE
Valid protocol-relative URLs show as errors / bad links

### ISSUE THREAD

**Issue by EmpireJones** [untitaker/hyperlink#112]
URLs without the protocol don't seem to work. They show as errors / bad links.

For example: `//example.com`

https://en.wikipedia.org/wiki/URL#prurl

**Comment by untitaker** [comment]
Can you confirm the version you're running on is relatively new? We do have code in place to handle those urls

**Comment by EmpireJones** [comment]
`hyperlink  --version`

> hyperlink 0.1.15

`rm -rf ./test && mkdir test && echo '<a href="https://works-example.com"></a><a href="//broken-example.com"></a>' > ./test/index.html && hyperlink ./test/index.html`

> Reading files
> Checking 1 links from 1 files (1 documents)
> ./test/index.html
>   error: bad link broken-example.com
> 
> Found 1 bad links

Anything I'm doing incorrectly?

Thanks!

**Comment by EmpireJones** [comment]
Oh, it looks like no new builds have been published since January, but the change was in May.

Any new release builds planned?

**Comment by EmpireJones** [comment]
Things seem to work fine in master.

**Comment by untitaker** [comment]
Released 0.1.16

**Comment by untitaker** [comment]
let me know there's anything else!
