### ISSUE TITLE
Publish Docker Image

### ISSUE THREAD

**Issue by fkorotkov** [untitaker/hyperlink#113]
It will be great to have a docker image that one can run locally or in CI instead of needing to install/download a binary.

**Comment by untitaker** [comment]
Feel free to create one, I'm happy to include it if you find there's a way it can be done on tag push

**Comment by untitaker** [comment]
it's probably not too much work but i don't have a usecase for it myself. so i would need somebody else to maintain (or at least co-maintain) it.

**Comment by untitaker** [comment]
in case it helps anybody, i just published an npm package for hyperlink. the reason for this is to use it in local development for existing static sites.

**Comment by untitaker** [comment]
hyperlink now has a basic docker image. let me know if it suits your needs
