### ISSUE TITLE
Url escapes are not normalized for local paths

### ISSUE THREAD

**Issue by BYK** [untitaker/hyperlink#135]
When a path has URL-unsafe characters, the URL to it gets escaped in the document but during link checking `hyperlink` does not unescape them to match the actual path, leading to errors like this:

```
Error: bad links:
  _next/static/chunks/pages/article/%5Bslug%5D-f92160effe6eedb195dc.js
```

The file `_next/static/chunks/pages/article/[slug]-f92160effe6eedb195dc.js` indeed exists on the disk.

**Comment by untitaker** [comment]
Hm yeah. I think we need to urldecode both the path and the url for normalization

On Fri, Nov 12, 2021, at 15:52, Burak Yigit Kaya wrote:
> 
> 
> When a path has URL-unsafe characters, the URL to it gets escaped in the document but during link checking `hyperlink` does not unescape them to match the actual path, leading to errors like this:
> 
> `Error: bad links:
>   _next/static/chunks/pages/article/%5Bslug%5D-f92160effe6eedb195dc.js
`

**Comment by untitaker** [comment]
I can get it fixed over the weekend, needs a new dependency on url. May want to copy lychees approach there which is a lot more sophisticated there iirc @mre

On Fri, Nov 12, 2021, at 15:56, Markus Unterwaditzer wrote:
> Hm yeah. I think we need to urldecode both the path and the url for normalization
> 
> On Fri, Nov 12, 2021, at 15:52, Burak Yigit Kaya wrote:
>> 
>> 
>> When a path has URL-unsafe characters, the URL to it gets escaped in the document but during link checking `hyperlink` does not unescape them to match the actual path, leading to errors like this:
>> 
>> `Error: bad links:
>>   _next/static/chunks/pages/article/%5Bslug%5D-f92160effe6eedb195dc.js
`

**Comment by untitaker** [comment]
should be fixed in 0.1.18

**Comment by mre** [comment]
Looks like you found a more lightweight solution than url. Good work. 👍

**Comment by untitaker** [comment]
Yeah ignore the ping, i remember that lychee either had a distinct Link or Href type and wasn't really sure if I overlooked something but I think that should be fine for now.

**Comment by BYK** [comment]
This was super fast, thanks a lot @untitaker! I was hoping to get a patch out myself but I need to bump up my Rust skills first :)

**Comment by untitaker** [comment]
lmk if you hit any other issues and then which ones you intend to work on!
