### ISSUE TITLE
Bad link to `/` has confusing error message

### ISSUE THREAD

**Issue by not-my-profile** [untitaker/hyperlink#138]
hyperlink apparently strips leading slashes which however results in a confusing error message when an `index.html` file in the base-path is missing:

```
% mkdir /tmp/test
% echo '<a href=/>test</a>' > /tmp/test/foo.html                   
% hyperlink /tmp/test                           
Reading files
Checking 1 links from 1 files (1 documents)
/tmp/test/foo.html
  error: bad link 

Found 1 bad links
```

Notice that it doesn't say what the bad link is.

**Comment by untitaker** [comment]
tempted to fix this by prepending `/` when formatting the error message
