### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by untitaker** [untitaker/hyperlink#145]
I found this program name impossible to google. I wonder if there's a better name

**Comment by cmdcolin** [comment]
just wanted to say, great project! very easy to set up in CI. I had previously been trying LinkChecker and it was significantly more difficult. just for ref, here's how i found this tool, googling specifically for broken link checker in CI

![Screenshot from 2023-02-21 12-06-36](https://user-images.githubusercontent.com/6511937/220436589-f28629b0-1e94-4f8f-8191-23b0060ec9f3.png)

**Comment by untitaker** [comment]
I can reproduce the search results. Now that you point it out that SEO is doing fine I guess I don't care about this issue anymore.
