### ISSUE TITLE
Add option "case insensitive"

### ISSUE THREAD

**Issue by Yuri05** [untitaker/hyperlink#147]
Is it possible to check anchors **case insensitive** or to add such an option?
E.g. when checking the html below, I get the error  `error: bad link test.html#Some-Section`
However both links `"#some-section"` and `"#Some-Section"` should be valid in my context.
Thank you.

```
<h1>Test</h1>

<a href="#some-section">link</a>
<a href="#Some-Section">link</a>

<h1 id="some-section">Some section</h1>
```

**Comment by untitaker** [comment]
are they valid because you're using JS? the provided html snippet, pasted into a html file and opened with firefox does not have both links working

**Comment by Yuri05** [comment]
For me both links work when opening the html e.g. in MS Edge (on Windows).
But in fact I am checking the cross references within (GitHub flavored) **Markdown** documents, which I convert to html first

**Comment by untitaker** [comment]
Can you try with other browsers? I don't have access to a windows machine

**Comment by Yuri05** [comment]
As I mentioned, my primary intention is to validate cross-references in (GitHub flavored) Markdown (_gfm_) documents.
Here is an example: https://github.com/Yuri05/TestReport/blob/main/test.md

In this file, there one chapter and one html anchor (which is supported by gfm) are defined:
```
<a id="introduction_anchor"></a>
## 1 Introduction
```

At the beginning of the document, 4 cross-references are defined:
```
# Valid links
[Valid chapter link](#1-introduction) <br>
[Valid chapter link case insensitive](#1-Introduction) <br>
[Valid anchor link](#introduction_anchor) <br>
[Valid anchor link case insensitive](#Introduction_Anchor) <br>
```

Now when I open this md file in a browser (on Windows) - all those 4 links work (tried it with Firefox, Edge and Chrome).
But when checking the converted html: 2 links are reported as invalid because of the case sensitive check
```
Error: bad anchors:
  test.html#1-Introduction
  test.html#Introduction_Anchor
```

**Comment by untitaker** [comment]
I don't think i can help here. You are converting the Markdown to HTML in a fundamentally different way than GitHub does. GitHub uses a ton of JS to make anchors work (the resulting DOM does not contain the element IDs verbatim), and for some reason they do it case-insensitively.

I think you have two options:

* You adjust your markdown conversion process to mimick what GitHub does to anchors.
* Use lychee, not hyperlink. It is a linkchecker that directly validates markdown files and the primary usecase is validating links in READMEs.

**Comment by Yuri05** [comment]
>Use lychee, not hyperlink. It is a linkchecker that directly validates markdown files and the primary usecase is validating links in READMEs. I am not sure whether it supports anchors in markdown files...

Already tried before - it does not :)

>... but if not, a feature request there would be more in-scope than here.

OK.

**Comment by untitaker** [comment]
maybe this helps: https://github.com/phseiff/github-flavored-markdown-to-html
