### ISSUE TITLE
Fails with urlencoded anchors

### ISSUE THREAD

**Issue by olemartinorg** [untitaker/hyperlink#154]
Our documentation contains some pages in English, and some in Norwegian. We use `hugo` to generate static pages. Norwegian is mostly ascii, but we have some special characters (æ, ø and å, along with their capitalized variants Æ, Ø and Å). When we create a link pointing to an anchor to a heading with one of these special characters, it seems `hugo` uses the special character in the heading `id` property (as is supported in HTML5), but links pointing to it will be urlencoded.

As an example, [this page](https://docs.altinn.studio/app/app-dev-course/modul3/) currently includes a link to the documentation page for how to deploy in the test environment (expand 'Deploy application' and click the first link under 'Useful documentation'). The link for this comes out to:

```html
<li><a href="/app/testing/deploy/#deploy-av-app-til-testmilj%C3%B8">Deploy app to test environment</a></li>
```

%C3%B8 is utf8 for 'ø'

In the target file, the anchor is defined as:

```html
<h2 id="deploy-av-app-til-testmiljø">Deploy av app til testmiljø</h2>
```

`hyperlink` thinks the link is broken, as it's not equal to the value in the header, but the link works fine in a browser.

Could this possibly be solved simply by url-decoding in [try_normalize_href_value](https://github.com/untitaker/hyperlink/blob/5dd593f77f3622b45c8006bcd5c0934565456460/src/html/parser.rs#L16)?

**Comment by untitaker** [comment]
I think we should add a call to `try_percent_decode` here: https://github.com/untitaker/hyperlink/blob/5dd593f77f3622b45c8006bcd5c0934565456460/src/html/mod.rs#L256-L258

Feel free to create a PR if you're inclined to fix this, otherwise I'll do it sometime this week.

**Comment by olemartinorg** [comment]
Nice! Turns out I didn't read the code thoroughly enough. I don't really know rust, but this seems simple enough for me to try to implement.
