### ISSUE TITLE
Optionally check `file://` links

### ISSUE THREAD

**Issue by not-my-profile** [untitaker/hyperlink#165]
I have a repository containing a crate and an mdbook. The doc comments in the crate link pages from the mdbook. I have a simple declarative macro that lets me define these links like:

```rs
#[doc = refBook!("bar", "/foo/bar.html")]
Bar,
```

The macro enables these links to either point to the `.html` files on the local file system (via `file:///` and `env!("CARGO_MANIFEST_DIR")`) or to the live website.

I'd now like to use `hyperlink` in the CI to check that these links aren't broken but `hyperlink` doesn't appear to check (or support to check) `file://` links.

**Comment by untitaker** [comment]
For my understanding. You are running hyperlink against rustdoc output in this scenario?

**Comment by not-my-profile** [comment]
Yes, exactly. The reason I'm detailing my use case is that I think normally there isn't a good reason why you'd even have `file://` links in static website builds. Here the deciding factors are that `env!("CARGO_MANIFEST_DIR")` returns an absolute path and that `rustdoc` does not appear to provide means of constructing a relative path relative to the manifest or output directory.

Full disclosure: I didn't even use the `file://` protocol initially ... absolute paths e.g. `href="/home/..."` still work when the containing file is opened in the browser via `file://`. However I think a `--resolve-absolute-paths-to-fs-root` flag would be more confusing than just `--check-file-uris`.

**Comment by not-my-profile** [comment]
Closing this, as I can just strip the absolute path from these links with `sed -i` and then copy the mdbook HTML into `target/doc` and hyperlink will work great :)

**Comment by untitaker** [comment]
i think a generic way to rewrite urls would be useful, for things like redirects which may not be reflected in HTML. as part of that one could solve this usecase.

but i currently don't have a use for it so i was not going to implement it
