### ISSUE TITLE
rust v1.73.0 error on install

### ISSUE THREAD

**Issue by Jaxii** [untitaker/hyperlink#166]
error[E0186]: method `should_emit_errors` has a `&mut self` declaration in the trait, but not in the impl
   --> C:\Users\jax\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyperlink-0.1.31\src\html\parser.rs:264:5
    |
264 |     fn should_emit_errors() -> bool {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut self` in impl
    |
    = note: `should_emit_errors` from trait: `fn(&mut Self) -> bool`

For more information about this error, try `rustc --explain E0186`.
error: could not compile `hyperlink` (bin "hyperlink") due to previous error

**Comment by untitaker** [comment]
is this with `cargo install`? try `cargo install --locked`

**Comment by untitaker** [comment]
no response, closing
