### ISSUE TITLE
prefix configuration

### ISSUE THREAD

**Issue by FreeMasen** [untitaker/hyperlink#167]
When deploying to some hosts, for example github pages, the site contents are required to live under a path prefix. This means that something like `<link href="/project-name/style.css" />` would fail to check unless an artificial directory is added before checking. Would you consider adding this as a configuration option?

**Comment by untitaker** [comment]
I believe it's easy (and performant) enough to add the artificial directory or to switch your SSG output to relative URLs, so I am inclined not to.
